# Generated by Django 5.0.7 on 2025-01-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetria', '0002_alter_mergedtelemetricdvb_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mergedtelemetricdvb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mergedtelemetricendcatchup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mergedtelemetricendvod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mergedtelemetricott',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mergedtelemetricstopcatchup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mergedtelemetricstopvod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='telemetria',
            options={},
        ),
    ]
